#!/usr/bin/env bash
#
# usage example:
#   $ , yarn --help
# This finds a derivation providing a bin/yarn, and runs it with `nix run`.
# If there are multiple candidates, the user chooses one using `fzy`.

[[ -z "$NIX_SYSTEM" ]] && NIX_SYSTEM="$(uname -m)-$(uname | tr '[:upper:]' '[:lower:]')"
[[ -z "$NIX_PROGRAMS_DB" ]] && NIX_PROGRAMS_DB="/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite"

set -euo pipefail

if [[ $# -lt 1 ]]; then
  >&2 echo "usage: , <program> [arguments]"
  exit 1
fi

if [[ "$1" == "--install" ]] || [[ "$1" == "-i" ]]; then
  install=1
  shift
else
  install=""
fi

argv0=$1; shift

case "${argv0}" in
  @OVERLAY_PACKAGES@)
    attr="${argv0}"
    ;;
  *)
    attr="$(sqlite3 "${NIX_PROGRAMS_DB}" "select package from Programs where system = \"$NIX_SYSTEM\" and name = \"$argv0\"")"
    if [[ "$(echo "${attr}" | wc -l)" -ne 1 ]]; then
      attr="$(echo "${attr}" | fzy)"
    fi
    ;;
esac

if [[ -z $attr ]]; then
  >&2 echo "no match"
  exit 1
fi

if [[ -n $install ]]; then
  nix-env -iA "nixpkgs.${attr%%.*}"
else
  nix run "nixpkgs.${attr}" -c "${argv0}" "$@"
fi
